def main(terminal, mainGui):
    terminal.troya_entry("<CLEAR>")
    mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
    terminal.troya_entry("qx")
    mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
    terminal.troya_entry("i")
    mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
    terminal.troya_entry("qcp/qsc")
    mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
    screen_output = terminal.troya_entry("<GETSCREEN>")
    result = screen_output.find('Q83')
    if result != -1:
        count_q83 = int(screen_output[result + 3:result + 9])
        result = screen_output.find('Q85')
        if result != -1:
            count_q85 = int(screen_output[result + 3:result + 9])
            f = open("Q85log.txt", "w+")
            terminal.troya_entry("q/qsc/85")
            mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
            for x in range(count_q85):
                screen_output = terminal.troya_entry("<GETSCREEN>")
                f.write(screen_output)
                f.write("\n***********************************************************\n\n\n")
                terminal.troya_entry("i")
                mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
            terminal.troya_entry("qx")
            mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
            terminal.troya_entry("i")
            mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
        else:
            count_q85 = 0
            terminal.troya_entry("q/qsc/83")
            mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
        for x in range(count_q83):
            terminal.troya_entry("qr")
            mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
            screen_output = terminal.troya_entry("<GETSCREEN>")
            if "please enter grps and grpf for group pnrs" in screen_output.lower():
                terminal.troya_entry("i")
                mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
        terminal.troya_entry("qx")
        mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
        terminal.troya_entry("i")
        mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
        terminal.troya_entry("qcp/qsc")
        mainGui.textBrowser.setText(terminal.troya_entry("<GETSCREEN>"))
        screen_output = terminal.troya_entry("<GETSCREEN>")
        result = screen_output.find('Q85')
        if count_q85 != int(screen_output[result + 3:result + 9]):
            print("Check Q85log.txt")
